name: CI Build and Artifact

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Show tool versions
        run: |
          java -version
          go version
          dotnet --info
          python --version

      - name: Install system deps (optional)
        run: |
          sudo apt-get update
          sudo apt-get install -y zip

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build artifact (zip project)
        run: |
          zip -r tovias-publishing-artifact.zip . -x '.git/*'

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: tovias-publishing-artifact
          path: tovias-publishing-artifact.zip
